<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Security_Management.aspx.cs" Inherits="QMSRSTools.VisioLinks.Security_Management" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <DIV>
        <H1 dir=ltr style="MARGIN: 3pt 0in; DIRECTION: ltr; TEXT-INDENT: 0in; unicode-bidi: embed; TEXT-ALIGN: left; mso-list: none; tab-stops: .5in"><A name=_Toc200951544></A><A name=_Toc200881340></A><A name=_Toc167608924><SPAN style="mso-bookmark: _Toc200881340"><SPAN style="mso-bookmark: _Toc200951544"><FONT face="Times New Roman" color=#000000 size=3>Security </FONT></SPAN></SPAN></A><FONT face="Times New Roman" color=#000000 size=3>Management</FONT></H1>
        <H2 dir=ltr style="MARGIN: 3pt 0in 3pt 0.25in; DIRECTION: ltr; TEXT-INDENT: 0in; unicode-bidi: embed; TEXT-ALIGN: left; mso-list: none; tab-stops: .5in"><?xml:namespace prefix = o ns = "urn:schemas-microsoft-com:office:office" /><o:p><FONT face="Times New Roman">&nbsp;</FONT></o:p></H2>
        <H2 dir=ltr style="MARGIN: 3pt 0in 3pt 0.25in; DIRECTION: ltr; TEXT-INDENT: 0in; unicode-bidi: embed; TEXT-ALIGN: left; mso-list: none; tab-stops: .5in"><o:p><FONT face="Times New Roman">&nbsp;</FONT></o:p></H2>
        <P class=IndentBullet dir=ltr style="MARGIN: 0in 0in 6pt; DIRECTION: ltr; TEXT-INDENT: 0in; unicode-bidi: embed; TEXT-ALIGN: left; mso-list: none; tab-stops: .5in"><SPAN lang=EN-AU style="FONT-FAMILY: 'Times New Roman','serif'"><FONT size=3>QMSRS and its employees are jointly, individually and collectively responsible for maintaining a secure workplace, and for the protection of QMSRS as well as client assets and information. <o:p></o:p></FONT></SPAN></P>
        <P class=IndentBullet dir=ltr style="MARGIN: 0in 0in 6pt 0.25in; DIRECTION: ltr; unicode-bidi: embed; TEXT-ALIGN: left"><SPAN style="FONT-SIZE: 8pt; FONT-FAMILY: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-ansi-language: EN-US"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN dir=ltr></SPAN><SPAN style="FONT-FAMILY: 'Times New Roman','serif'; mso-bidi-font-weight: bold; mso-ansi-language: EN-US"><FONT size=3>QMSRS protects QMSRS employees, facilities and assets globally in the following areas: <o:p></o:p></FONT></SPAN></P>
        <P class=IndentBullet dir=ltr style="MARGIN: 0in 0in 6pt 0.75in; DIRECTION: ltr; unicode-bidi: embed; TEXT-ALIGN: left; tab-stops: list .75in"><SPAN style="FONT-SIZE: 8pt; FONT-FAMILY: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-ansi-language: EN-US"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN dir=ltr></SPAN><SPAN style="FONT-FAMILY: 'Times New Roman','serif'; mso-bidi-font-weight: bold; mso-ansi-language: EN-US"><FONT size=3><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;</SPAN>Physical Security Systems <o:p></o:p></FONT></SPAN></P>
        <P class=IndentBullet dir=ltr style="MARGIN: 0in 0in 6pt 0.75in; DIRECTION: ltr; unicode-bidi: embed; TEXT-ALIGN: left; tab-stops: list .75in"><SPAN style="FONT-SIZE: 8pt; FONT-FAMILY: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-ansi-language: EN-US"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN dir=ltr></SPAN><SPAN style="FONT-FAMILY: 'Times New Roman','serif'; mso-bidi-font-weight: bold; mso-ansi-language: EN-US"><FONT size=3><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;</SPAN><?xml:namespace prefix = st1 ns = "urn:schemas-microsoft-com:office:smarttags" /><st1:place w:st="on"><st1:City w:st="on">Enterprise</st1:City></st1:place> Access Control Security <o:p></o:p></FONT></SPAN></P>
        <P class=IndentBullet dir=ltr style="MARGIN: 0in 0in 6pt 0.75in; DIRECTION: ltr; unicode-bidi: embed; TEXT-ALIGN: left; tab-stops: list .75in"><SPAN style="FONT-SIZE: 8pt; FONT-FAMILY: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-ansi-language: EN-US"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN dir=ltr></SPAN><SPAN style="FONT-FAMILY: 'Times New Roman','serif'; mso-bidi-font-weight: bold; mso-ansi-language: EN-US"><FONT size=3><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;</SPAN>Systems and Monitoring <o:p></o:p></FONT></SPAN></P>
        <P class=IndentBullet dir=ltr style="MARGIN: 0in 0in 6pt 0.75in; DIRECTION: ltr; unicode-bidi: embed; TEXT-ALIGN: left; tab-stops: list .75in"><SPAN style="FONT-SIZE: 8pt; FONT-FAMILY: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-ansi-language: EN-US"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN dir=ltr></SPAN><SPAN style="FONT-FAMILY: 'Times New Roman','serif'; mso-bidi-font-weight: bold; mso-ansi-language: EN-US"><FONT size=3><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;</SPAN>Executive Support <o:p></o:p></FONT></SPAN></P>
        <P class=IndentBullet dir=ltr style="MARGIN: 0in 0in 6pt 0.75in; DIRECTION: ltr; unicode-bidi: embed; TEXT-ALIGN: left; tab-stops: list .75in"><SPAN style="FONT-SIZE: 8pt; FONT-FAMILY: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-ansi-language: EN-US"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN dir=ltr></SPAN><SPAN style="FONT-FAMILY: 'Times New Roman','serif'; mso-bidi-font-weight: bold; mso-ansi-language: EN-US"><FONT size=3><SPAN style="mso-spacerun: yes">&nbsp;&nbsp;</SPAN>Crisis Management Coordination<o:p></o:p></FONT></SPAN></P>
        <P class=IndentBullet dir=ltr style="MARGIN: 0in 0in 6pt 0.25in; DIRECTION: ltr; unicode-bidi: embed; TEXT-ALIGN: left"><SPAN style="FONT-SIZE: 8pt; FONT-FAMILY: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol; mso-bidi-font-weight: bold; mso-bidi-font-size: 10.0pt; mso-ansi-language: EN-US"><SPAN style="mso-list: Ignore">·<SPAN style="FONT: 7pt 'Times New Roman'">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </SPAN></SPAN></SPAN><SPAN dir=ltr></SPAN><SPAN style="FONT-FAMILY: 'Times New Roman','serif'; mso-ansi-language: EN-US"><FONT size=3>QMSRS monitors and reports QMSRS adherence to security and privacy policies and control standards that comply with applicable key industry regulations, standards, and best practices.<SPAN style="mso-spacerun: yes">&nbsp; </SPAN><SPAN style="mso-bidi-font-weight: bold"><o:p></o:p></SPAN></FONT></SPAN></P>
        <P class=MsoNormal dir=ltr style="MARGIN: 0in 0in 0pt; DIRECTION: ltr; unicode-bidi: embed; TEXT-ALIGN: left"><SPAN style="mso-bidi-language: AR-JO"><o:p><FONT face="Times New Roman" size=3>&nbsp;</FONT></o:p></SPAN></P>
    </div>
    </form>
</body>
</html>
